# Logo
logo_image_source: \assets\4balloon.svg

# Index Page
index_banner_text: Welcome to Tian's Blog
index_banner_text_secondary: Web FE. Diary. Jay Chou. And Else.
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Contact: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM DD. YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://tva2.sinaimg.cn/crop.0.0.1152.1152.180/bfe3e06cjw8erzjurci75j20w00w0q5f.jpg
about_widget_text: "My name is Tian Wang and this is my blog.<br>I am a web front-end engineer.<br> I currently live and work in GuangZhou, China. The blog is just a baby now, I'll make it better."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Comments.
git_comments:
  # owner: "tianwang8090"
  # repo: "comments4blog"
  # client_id: 6ea6773cfba91f9afa91
  # client_secret: e1dda4f16de9fb3dcf6056a9c6f07aa6acde7fc3

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: http://weibo.com/u/3219382380/
    fa_icon: fa-weibo 
  - url: https://github.com/tianwang8090
    fa_icon: fa-github
  - url: mailto:tianwang8090@163.com
    fa_icon: fa-envelope
  # - url: /#
  #   fa_icon: fa-rss

# Footer about
footer_about: "<a class=\"link dim white\" href=\"http://weibo.com/u/3219382380/\">@tian田小旺</a>. All right reserved | Design & Hexo "
